name: xpense_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  web:
      generate: true
      image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Bold.ttf
        - asset: assets/fonts/HindSiliguri-Light.ttf
        - asset: assets/fonts/HindSiliguri-Medium.ttf
        - asset: assets/fonts/HindSiliguri-Regular.ttf
        - asset: assets/fonts/HindSiliguri-SemiBold.ttf
